name: apt-offline-download

on:
  workflow_dispatch:

jobs:
  apt-offline:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install apt-offline
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-offline

      - name: Download apt offline bundle
        run: |
          mkdir -p downloads
          apt-offline get update.sig --bundle downloads/update.zip

      - name: Commit bundle
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add downloads/update.zip
          git commit -m "Add apt-offline update bundle" || echo "Nothing to commit"
          git push
